trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - '**/*.md'

variables:
  DOTNET_VERSION: 6.0.300
  MACOS_VM_IMAGE: 'macos-12'

jobs:
- job: macOS
  pool:
    vmImage: $(MACOS_VM_IMAGE)
  steps:
    - task: UseDotNet@2
      displayName: .NET Version
      inputs:
        packageType: 'sdk'
        version: '$(DOTNET_VERSION)'

    - task: Bash@3
      displayName: Install MAUI
      inputs:
        targetType: 'inline'
        script: |
          dotnet nuget locals all --clear
          dotnet workload install ios \
            --source https://aka.ms/dotnet6/nuget/index.json \
            --source https://api.nuget.org/v3/index.json

    - task: Bash@3
      displayName: Build iOS App
      inputs:
        targetType: 'inline'
        script: |
          dotnet build -f net6.0-ios -c Release
