trigger:
  branches:
    include:
      - '*'
  paths:
    exclude:
      - '**/*.md'

variables:
- template: templates/vars.yml

jobs:
- job: macOS
  pool:
    vmImage: $(MACOS_VM_IMAGE)
  steps:
    - template: templates/setup-dotnet.yml

    - task: Bash@3
      displayName: Build iOS App
      inputs:
        targetType: 'inline'
        script: |
          dotnet build -f net6.0-ios -c Release -v Detailed
